### ISSUE TITLE
Animation bug

### ISSUE THREAD

**Issue by 00c** [minetest-mods/playeranim#11]
When pressing F7 player hands are Up, When hitting item they move down.
It is visible only when you look from side on yourself. 
Running recent minetest_game and minetest server

**Comment by kingoscargames** [comment]
Configuration

This mod supports 2 versions of the player model:

The old version: v1 (before nov. 2016)
The new version: v2 (after nov. 2016) (see also init.lua)
As there is no automatic way to determine which version is used, this must be manually configured in init.lua.

Symptoms of having configured the incorrect player model:

In rest, arms are raised up, and are either detached from the body, or are too close to the body
Cape (if visible) points upward
