### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest-mods/playeranim#3]
Crashed when a player joins.
Debug:
```
 ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'playeranim' in callback environment_Step(): ...ad7f-win64\bin - Copy\..\mods\playeranim-master\init.lua:277: attempt to index a nil value
 ERROR[Main]: stack traceback:
 ERROR[Main]: 	...ad7f-win64\bin - Copy\..\mods\playeranim-master\init.lua:277: in function 'animate_player'
 ERROR[Main]: 	...ad7f-win64\bin - Copy\..\mods\playeranim-master\init.lua:323: in function <...ad7f-win64\bin - Copy\..\mods\playeranim-master\init.lua:321>
 ERROR[Main]: 	...-7c321ad7f-win64\bin - Copy\..\builtin\game\register.lua:425: in function <...-7c321ad7f-win64\bin - Copy\..\builtin\game\register.lua:409>
```

**Comment by SmallJoker** [comment]
Which Minetest version are you using server-side? Currently this error is impossible.

`get_animation` ensures it's not a nil value, for both 5.5.0 ...

https://github.com/minetest/minetest_game/blob/638099c9999e46b9a7204858b2a7c7a1efb2f94c/mods/player_api/api.lua#L56-L62

.. and older versions (should include 0.4.x too) :

https://github.com/minetest/minetest_game/blob/75f957555751ae9a6fad6c7c6772bf1bcc89cf38/mods/player_api/api.lua#L26-L33

Please check whether there's another mod that overwrites `player_api.get_animation` and fix its implementation accordingly. This function must return a table as documented here:

https://github.com/minetest/minetest_game/blob/master/game_api.txt#L481-L484

Invalid issue.

**Comment by IrrlichtMt4** [comment]
Crashes in Minetest 5.5.0.
With this error 

```
AsyncErr: Lua: Runtime error from mod 'playeranim' in callback environment_Step(): ...etest-5.5.0-win64\bin\..\mods\playeranim-master\init.lua:277: attempt to index a nil value
stack traceback:
	...etest-5.5.0-win64\bin\..\mods\playeranim-master\init.lua:277: in function 'animate_player'
	...etest-5.5.0-win64\bin\..\mods\playeranim-master\init.lua:323: in function <...etest-5.5.0-win64\bin\..\mods\playeranim-master\init.lua:321>
	...1)\minetest-5.5.0-win64\bin\..\builtin\game\register.lua:425: in function <...1)\minetest-5.5.0-win64\bin\..\builtin\game\register.lua:409>
```

I tested in the older version the crash did not happen. Versions that did not crash are versions 5.4 and under.

**Comment by SmallJoker** [comment]
This is the same error message as above. Please check for mods that override `player_api.get_animation` and add log messages to the relevant code paths (`animate_player` and `player_api.get_animation`). Also provide exact reproduction steps so that I can debug and fix this issue.

**Comment by IrrlichtMt4** [comment]
Steps are:

1. Enable playeranim without any other mods.

2. Make sure to have the newest version of minetest_game ans have the newest stable or dev version of Minetest (5.5.0 or 5.6.0-dev.

3. Join your world. 

4. Observe crash when you join your world.

**Comment by SmallJoker** [comment]
![screenshot_20220406_193343](https://user-images.githubusercontent.com/1497498/162034424-74e90c81-3a1c-406b-b233-e6f56b893de8.jpg)

Cannot reproduce. Works for me using the newest Minetest Game (master) and a recent Minetest 5.6.0-dev version.

**Comment by IrrlichtMt4** [comment]
Closing issue as I found out that https://github.com/BlockySurvival/playeranim does not crash the game. Thanks for helping anyways. :)

**Comment by SmallJoker** [comment]
@IrrlichtMt4 With some luck (and coincidence) I was able to reproduce this issue. The most important part about this bug can be found one line above the error, a warning stating `get_animation called on offline player` (from player_api).

Workaround added in e0acae8. Issue fixed.

**Comment by IrrlichtMt4** [comment]
Thanks :)
