### ISSUE TITLE
CDB

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/playeranim#4]
why is this mod not in the content DB?

**Comment by SmallJoker** [comment]
@rubenwardy How are minetest-mods mods added to the CDB? They're now a community project and don't quite belong to a single author.

**Comment by rubenwardy** [comment]
It's up to the author / minetest-mods. Editors can upload mods on behalf of an author. Another option would be to create a "minetest-mods" user like how "mt-mods" has

**Comment by appgurueu** [comment]
~~https://content.minetest.net/packages/LMD/character_anim/ is superior anyways~~

**Comment by SmallJoker** [comment]
https://content.minetest.net/packages/Rui/playeranim/

Queued for approval...
