### ISSUE TITLE
Error Calling Method "get_look_vertical"

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/playeranim#4]
When I try to start a singleplayer game with this mod I get the following error:

    ServerError: Runtime error from mod 'playeranim' in callback environment_Step(): ...test/minetest-game-antum/mods/player/playeranim/init.lua:175: attempt to call method 'get_look_vertical' (a nil value)

My system & Minetest info:

    OS: Linux Mint 18 64-bit

    $ uname -spr
    Linux 4.4.0-31-generic x86_64

    $ minetest --version
    Minetest 0.4.14 (Linux)
    Using Irrlicht 1.8.3
    Build info: VER=0.4.14 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"

**Comment by Rui914** [comment]
get_look_vertical is added in Minetest on 18 Jun. (https://github.com/minetest/minetest/pull/4229)
What you need is newer version minetest. You can download that here: https://code.launchpad.net/~minetestdevs/+archive/daily-builds/+packages

Or you can download older version playeranim here:
https://github.com/minetest-mods/playeranim/archive/62b49dc0d88d7b58f53ca59e17a917cccda556f7.zip

**Comment by AntumDeluge** [comment]
Thank you very much. I installed the older version like you recommended & it works great.
