### ISSUE TITLE
Force push repo removed original licensing clause

### ISSUE THREAD

**Issue by sofar** [minetest-mods/playeranim#6]
the old license read:

```
+Copyright (C) 2013-2014, Diego Martínez All rights reserved.
+
+Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
+
+Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
+
+Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
```

Even though this is retained now as `license_original.txt`, I feel it's disingenuous to move it to another file and replace the actual text with a different set of license conditions. The code has not changed, so relicensing isn't kosher here.

I consider this a potential license violation. Let's solve this properly, please.

**Comment by sofar** [comment]
@Rui-Minetest please comment, asap.

**Comment by Rui-Minetest** [comment]
I'll revert license to the original license.

**Comment by Rui-Minetest** [comment]
@sofar 
Is it ok with you?

**Comment by sofar** [comment]
Yeah, that's fine. Thanks for fixing that quickly.
